### ISSUE TITLE
[Question] About always calling ParseMultiIEs(i.Payload) in helper function

### ISSUE THREAD

**Issue by tim-ywliu** [wmnsk/go-pfcp#120]
I found many helper functions will ParseMultiIEs(i.Payload) directly even it was already parsed. Fox example:
```
func (i *IE) CreatePDR() ([]*IE, error) {
	if i.Type != CreatePDR {
		return nil, &InvalidTypeError{Type: i.Type}
	}

	return ParseMultiIEs(i.Payload)
}
```

I think it can enhance performance to add ChildIEs length checking to determine if this IE was parsed.
```
func (i *IE) CreatePDR() ([]*IE, error) {
	if i.Type != CreatePDR {
		return nil, &InvalidTypeError{Type: i.Type}
	}
	if len(i.ChildIEs) > 0 {
		return i.ChildIEs
	}
	return ParseMultiIEs(i.Payload)
}
```

Or something I missed?

**Comment by wmnsk** [comment]
sounds legit, but let me have a closer look into codes, as I don't actually remember what was the idea behind calling ParseMultiIEs here TBH :sweat_smile:

**Comment by wmnsk** [comment]
I agree, in most real use-cases the child IEs are already parsed it seems, and your idea can improve performance. Can you work on it? Otherwise I'll do it in my spare time (with not-so-high priority).

**Comment by wmnsk** [comment]
Clarified how to handle grouped IEs efficiently in README. I will leave these `<IE-Name>()` methods as they are for consistency/for specific purpose.

https://github.com/wmnsk/go-pfcp#retrieving-values-from-ies

**Comment by tim-ywliu** [comment]
Thanks!
