### ISSUE TITLE
How to distinguish the type of IE from the protocol

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#13]
![image](https://user-images.githubusercontent.com/22961061/78894685-1b52f900-7aa0-11ea-85cb-97a10ba59dda.png)
![image](https://user-images.githubusercontent.com/22961061/78894703-2443ca80-7aa0-11ea-8900-1bbfccee13f1.png)
It's like this, I researched and understood that the news is just a combination of various IEs, and some IEs are also a combination of other IEs. I found that the IE codes given in the agreement are those independent IE. Therefore, I want to finish the independent IE that has not been completed first.I would like to ask, how do you determine what type of IE this IE belongs to through the agreement.

**Comment by wmnsk** [comment]
The private constructors(`newXyzIE`) are just the internal helpers for us which can only be used for simple IEs like QFI, BAR ID, etc.

https://github.com/wmnsk/go-pfcp/search?q=newUint8ValIE&type=Code

The complicated IEs like F-TEID has the struct named `IENameField` with dedicated decoder/encoder methods. Please see the actual implementation of F-TEID to see how it's implemented.

https://github.com/wmnsk/go-pfcp/blob/eb243bc34eeffe87c4ab56783575ba801b9a120d/ie/f-teid.go

**Comment by w910820618** [comment]
agreement == **https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/14.00.00_60/ts_129244v140000p.pdf**

**Comment by wmnsk** [comment]
Specification? OK. Nothing about the details of implementation are explained there. We need to interpret how to implement from what’s described in that document.

**Comment by w910820618** [comment]
![image](https://user-images.githubusercontent.com/22961061/78994909-c680b280-7b73-11ea-894a-ff4600df7660.png)
![image](https://user-images.githubusercontent.com/22961061/78994875-b7016980-7b73-11ea-8cb5-6e84400d15e1.png)
Why is F-SEID uint64?ChooseID, which is not specified in Specification, why should you declare it?
My question may be a bit simple for you. But this is my first research on Specification, and thank you for your answer.

**Comment by w910820618** [comment]
![image](https://user-images.githubusercontent.com/22961061/78995198-69393100-7b74-11ea-813b-835eae1cfa3f.png)
![image](https://user-images.githubusercontent.com/22961061/78995177-5c1c4200-7b74-11ea-9f15-c407413ff260.png)
My question may be a bit simple for you. But this is my first research on Specification, and thank you for your answer.
Why the SEID is uint64?I think there is no ChooseID in the form, why should you declare it?

**Comment by wmnsk** [comment]
* `6 to 13` on the left of SEID in Figure 8.2.37-1 means that it’s 64bit long.
* ChooseID looks a mistake of me 😖

By the way, could you paste the URL or the code itself like this when you refer to some source code, as screenshots are not search-friendly, and the representation of your editor is not always commonly recognized by other people as well.

https://github.com/wmnsk/go-pfcp/blob/master/ie/f-seid.go#L40-L46
