### ISSUE TITLE
Why is the flag in f_teid calculated like this?

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#14]
https://github.com/wmnsk/go-pfcp/blob/0be588279bd665228654cddb9d160cc1d3009993/ie/f-teid.go#L103

https://github.com/wmnsk/go-pfcp/blob/0be588279bd665228654cddb9d160cc1d3009993/ie/f-teid.go#L113

I read the introduction about f_teid in TS29244, but I do n’t understand why you want to calculate the flag like this? Can you explain?

**Comment by wmnsk** [comment]
If it's about the the sequence of v4 and v6, fixed in #15(swapped v4 and v6).

From the next time, could you let me know what exactly is your question(=what do you think is wrong with my implementation)? It's a waste of time & resources for both of us to confirm if we're on the same page.
