### ISSUE TITLE
Encapsulate user-plane-ip-resource-information IE

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#16]
![image](https://user-images.githubusercontent.com/22961061/79407917-ae25f300-7fcc-11ea-99a8-599235b04465.png)
You can use this IE, give me an example, how do you encapsulate it? For example, how do you judge the type of each field in IE?

The following code is packaged according to my understanding. Can you see what is wrong?
```
type UserPlaneIpResourceInformation struct {
	Flags           uint8
	TEIDRange       uint32
	IPv4            net.IP
	IPv6            net.IP
	NetworkInstance string
	SourceInterface uint8
}
```
What types should TEIDRange, NetworkInstance, and SourceInterface take?

Thank you for your help and guidance

**Comment by w910820618** [comment]
I refer to your implementation of the structure in [f-seid](https://github.com/wmnsk/go-pfcp/blob/master/ie/f-seid.go) ---> https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/f-seid.go#L40 .
Are Flags in the structure used to control Octets5? 
https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/f-seid.go#L113
https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/f-seid.go#L103
Are these two methods used to assign values to Octet5?

**Comment by w910820618** [comment]
![image](https://user-images.githubusercontent.com/22961061/79409934-b3397100-7fd1-11ea-8bb2-5362a809a167.png)
Take a look, is my understanding correct?How do you think TEIDRIFlags should be assigned?
![bf24e450dd9356ff99fb94561e79c78](https://user-images.githubusercontent.com/22961061/79410469-17106980-7fd3-11ea-9601-82ef88135a6a.jpg)

**Comment by w910820618** [comment]
> Octets "k to l", if present, shall contain a Network Instance value as encoded in octet "5 to n+4" of the Figure 8.2.4-1 in clause 8.2.4, identifying a Network Instance with which the IP address or TEID Range is associated.
> Octet r, if present, shall contain a Source Interface value as encoded in octet 5 of the Figure 8.2.2-1 in clause 8.2.2, identifying the Source Interface with which the IP address or TEID Range is associated.

The meaning of the two sentences is to put the value encoded by Network Instance and Source Interface into user-plane-ip-resource-information?

**Comment by wmnsk** [comment]
@w910820618 
Did you solve it?

**Comment by w910820618** [comment]
@wmnsk I did not solve this problem

**Comment by wmnsk** [comment]
Please refer to [the implementation I've just pushed](https://github.com/wmnsk/go-pfcp/blob/a5d43d8c8eb7f8d5661206467bc84b75f2d72986/ie/user-plane-ip-resource-information.go) and find the answer by yourself, as there are too many things to explain.

The specification by 3GPP is sometimes(or often) not so kind to us. We need to supplement some parts with our consideration made as reasonable as possible.

**Comment by w910820618** [comment]
thank you!!!

**Comment by wmnsk** [comment]
Closing, as it seems there's no questions.
