### ISSUE TITLE
About PFD contents IE encoding

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#17]
![image](https://user-images.githubusercontent.com/22961061/79722096-0d11a200-8316-11ea-91e8-0fe967cabc8c.png)

https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/pfd-contents.go#L386-L395

Can you help check your encoding problem?

**Comment by wmnsk** [comment]
Could you share the PCAP and the code that you created that packets?

**Comment by w910820618** [comment]
```go
//IE required for encapsulation
	pfdContents := ie.NewPFDContents("11", "192.168.2.130", "11", "11", "11", []string{"11", "22"}, nil, nil)
	pfdContent := ie.NewPFDContext(pfdContents)
	applictionID := ie.NewApplicationID("1")
	applictionIDsPFDs := ie.NewApplicationIDsPFDs(applictionID, pfdContent)

	acreq, err := message.NewPFDManagementRequest(applictionIDsPFDs).Marshal()
```

**Comment by wmnsk** [comment]
OK, I'll take a look within this week.
It'd be nicer(=my investigation could be done quickly) if you could share PCAP with me in advance.

**Comment by w910820618** [comment]
[s_4.zip](https://github.com/wmnsk/go-pfcp/files/4507024/s_4.zip)
This is my PCAP file！！！

**Comment by wmnsk** [comment]
This is also a problem on Wireshark side like #19. With [this patch](https://code.wireshark.org/review/c/36909/), this PCAP is shown as expected like this.

[go-pfcp_issue17.pcapng.gz](https://github.com/wmnsk/go-pfcp/files/4521585/go-pfcp_issue17.pcapng.gz)

https://gist.github.com/wmnsk/d08ca653472a594faca962620a98f7d3

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/6134010/80084034-4bff5c00-8591-11ea-894a-8151251ec32f.png">

**Comment by w910820618** [comment]
Do you mean that this is caused by a bug in wireshark, is that true?

**Comment by wmnsk** [comment]
Exactly, and now it's fixed and merged to master 🎉

I don't know when it'll be shipped, but for sure some day we'll see it right. If you need it right now, you need to build Wireshark from the source with this patch: https://code.wireshark.org/review/c/36909/
