### ISSUE TITLE
How to distinguish between different FQ CSID

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#18]
![image](https://user-images.githubusercontent.com/22961061/79930152-567b0200-847a-11ea-8888-9de086f09c02.png)
I would like to ask, how to distinguish these different FQ-CSIDs when assigning values?

**Comment by w910820618** [comment]
https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/fq-csid.go#L21-L52

**Comment by wmnsk** [comment]
I think there's nothing to distinguish those inside the IE. It's determined by the type of message and node type of the sender.

As described in section 8.2.43 in TS 29.244, the FQ-CSID doesn't have such field.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/6134010/79969317-4be95880-84cc-11ea-86a5-c478118c6a1c.png">

And, clause 23 of TS 23.007 says it's a local parameter that is assigned by the nodes themselves and to be told to their peers. So, if it's sent by S-GW-C, it's regarded as S-GW-C FQ-CSID.

```
With the exception of the GTPv2 Delete PDN Connection Set Request and PMIPv6 Binding Revocation Indication BRI messages, each feature supporting MME, SGW, ePDG, TWAN or PGW shall assign only one FQ-CSID for itself in messages and each FQ-CSID shall have exactly one CSID within the FQ-CSID.
```
