### ISSUE TITLE
Remote GTPU Peer IE encoding problem

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#19]
My encapsulation code：
```go
dl := ie.NewDestinationInterface(1)
nt := ie.NewNetworkInstance("11")
ie.NewRemoteGTPUPeer("192.168.2.1", "", dl, nt)
```
Your encapsulation logic
https://github.com/wmnsk/go-pfcp/blob/e45192efda6dfa49fcf49f101a8c724e7cafc04e/ie/remote-gtp-u-peer.go#L197-L212

PCAP file
[s_5.zip](https://github.com/wmnsk/go-pfcp/files/4513487/s_5.zip)

**Comment by wmnsk** [comment]
We have two problems for this issue.

1. Misunderstanding of its encoding

I thought the DI and NI should be encoded as a whole IE but it should just have the payloads. PR#20 will fix this issue. Only with this fix, the packet looks like this.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/6134010/79987460-67625c80-84e8-11ea-8a29-9f14f3cca24e.png">

2. Wireshark dissector is incorrect
I sent a patch to Wireshark with the fix of the length. Follow the discussion [here](https://code.wireshark.org/review/c/36908/) if you're interested.

With both changes, the packet looks valid like this.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/6134010/79987719-bdcf9b00-84e8-11ea-9405-7d6f6d7d0c5f.png">

https://gist.github.com/wmnsk/e95cce7623ff03d7ddacd77cc7ffc53d

[remote-gtpu-peer.pcapng.gz](https://github.com/wmnsk/go-pfcp/files/4516349/remote-gtpu-peer.pcapng.gz)
