### ISSUE TITLE
How to code 3GPP Interface Type

### ISSUE THREAD

**Issue by w910820618** [wmnsk/go-pfcp#21]
![image](https://user-images.githubusercontent.com/22961061/80079409-d4c2cb80-8582-11ea-9511-51bdf4dbb5e2.png)

How to express 6 bits binary integer in golang? Thanks, guidance

**Comment by wmnsk** [comment]
It's very basic format. Look for a similar IE that is available in [ie package](https://github.com/wmnsk/go-pfcp/tree/master/ie) and implement like that.

By the way, to be honest, I'm getting to be stressed a bit with your attitude. To continue collaborating, please try to communicate in clear words, don't close issues/PRs without saying anything. I'm not a coding robot :(

**Comment by w910820618** [comment]
Sorry, I will pay attention to my communication in the future. Thank you very much for your help, this is also my first transnational cooperation. Thank you.

**Comment by wmnsk** [comment]
Thank you for understanding 😃 
Since we have different backgrounds and experiences, I think the communication in words is really important. Let's get in close touch and make the project better!
