### ISSUE TITLE
Optional params in grouped IE

### ISSUE THREAD

**Issue by vulcanfan** [wmnsk/go-pfcp#48]
Hi,
Most IEs in 29.244 are optional or conditional.
But from what I can see, the functions such as NewPDI() expect all parameters to be present and non-nil.
If any parmeter is nil, eg to indicate that the application doesn't wish to specify that parm, then the code fails within ie.newGroupedIE() because it tries to dereference pointers at line 563, without checking for nil ones, as it ranges through the provided child IEs, some of which will be nil.
Or have I misunderstood how optional parameters are skipped when creating IEs (or messages)?
Thanks

**Comment by wmnsk** [comment]
Seems so but let me review the implementation and consider how to fix it.

**Comment by wmnsk** [comment]
Please check the behavior with the latest version, thanks.

**Comment by vulcanfan** [comment]
Thanks very much!  Will do.
________________________________
