### ISSUE TITLE
array of UserPlaneIPinformation?

### ISSUE THREAD

**Issue by krsna1729** [wmnsk/go-pfcp#55]
Commit https://github.com/wmnsk/go-pfcp/commit/b6fbe253efe64f2651aa581398937b5c65cfb2af introduced parsing of  `UserPlaneIPResourceInformation` for association setup response but allows only one ie of that type. We were looking at upf which sends some flows to N9 vs N6, The SMF would probably need to know the Core IP and we were thinking of sending it via AssociationSetupRespoinse. We cannot do that anymore since Access details get overwritten with Core details. Does this sound right? Should i send 2 responses instead?

@TheWayYouMakeMeFeel  @wmnsk 

Library

```go
		case ie.UserPlaneIPResourceInformation:
			m.UserPlaneIPResourceInformation = i
```

App

```go
	asres, err := message.NewAssociationSetupResponse(asreq.SequenceNumber,
		ie.NewRecoveryTimeStamp(time.Now()),
		ie.NewNodeID(sourceIP, "", ""),       /* node id (IPv4) */
		ie.NewCause(ie.CauseRequestAccepted), /* accept it blindly for the time being */
		// 0x41 = Spare (0) | Assoc Src Inst (1) | Assoc Net Inst (0) | Tied Range (000) | IPV6 (0) | IPV4 (1)
		//      = 01000001
		ie.NewUserPlaneIPResourceInformation(0x41, 0, accessIP, "", "", ie.SrcInterfaceAccess),
		//ie.NewUserPlaneIPResourceInformation(0x41, 0, coreIP, "", "", ie.SrcInterfaceCore),
	).Marshal() /* userplane ip resource info */
```

/cc @badhrinathpa @thakurajayL

**Comment by TheWayYouMakeMeFeel** [comment]
@krsna1729 Hi, sorry for seeing your question too late. It's my bad for missing so much arrays in the pr https://github.com/wmnsk/go-pfcp/pull/52
The code can be fix as follows. And I believe there must be lots of IEs need to be fix like this, I did not do the work perfect in the pr above, hope we can do it together.
`+++ b/message/association-setup-response.go
@@ -16,7 +16,7 @@ type AssociationSetupResponse struct {
        RecoveryTimeStamp              *ie.IE
        UPFunctionFeatures             *ie.IE
        CPFunctionFeatures             *ie.IE
-       UserPlaneIPResourceInformation *ie.IE
+       UserPlaneIPResourceInformation []*ie.IE
        AlternativeSMFIPAddress        *ie.IE
        PFCPASRspFlags                 *ie.IE
        UEIPAddressPoolInformation     *ie.IE
@@ -49,7 +49,7 @@ func NewAssociationSetupResponse(seq uint32, ies ...*ie.IE) *AssociationSetupRes
                case ie.CPFunctionFeatures:
                        m.CPFunctionFeatures = i
                case ie.UserPlaneIPResourceInformation:
-                       m.UserPlaneIPResourceInformation = i
+                       m.UserPlaneIPResourceInformation = append(m.UserPlaneIPResourceInformation, i)
                case ie.AlternativeSMFIPAddress:
                        m.AlternativeSMFIPAddress = i
                case ie.PFCPASRspFlags:
@@ -119,7 +119,7 @@ func (m *AssociationSetupResponse) MarshalTo(b []byte) error {
                }
                offset += i.MarshalLen()
        }
-       if i := m.UserPlaneIPResourceInformation; i != nil {
+       for _, i := range m.UserPlaneIPResourceInformation {
                if err := i.MarshalTo(m.Payload[offset:]); err != nil {
                        return err
                }
@@ -214,7 +214,7 @@ func (m *AssociationSetupResponse) UnmarshalBinary(b []byte) error {
                case ie.CPFunctionFeatures:
                        m.CPFunctionFeatures = i
                case ie.UserPlaneIPResourceInformation:
-                       m.UserPlaneIPResourceInformation = i
+                       m.UserPlaneIPResourceInformation = append(m.UserPlaneIPResourceInformation, i)
                case ie.AlternativeSMFIPAddress:
                        m.AlternativeSMFIPAddress = i
                case ie.PFCPASRspFlags:
@@ -254,7 +254,7 @@ func (m *AssociationSetupResponse) MarshalLen() int {
        if i := m.CPFunctionFeatures; i != nil {
                l += i.MarshalLen()
        }
-       if i := m.UserPlaneIPResourceInformation; i != nil {
+       for _, i := range m.UserPlaneIPResourceInformation {
                l += i.MarshalLen()
        }
        if i := m.AlternativeSMFIPAddress; i != nil {
`

**Comment by wmnsk** [comment]
That's no one's fault. Thank you for reporting @krsna1729 and thank you for fixing @TheWayYouMakeMeFeel 👍
