### ISSUE TITLE
User-id ie NAI flag problem

### ISSUE THREAD

**Issue by chengtontom** [wmnsk/go-pfcp#88]
https://github.com/wmnsk/go-pfcp/blob/fbac02500b1df919852146f072a0900b2ce6be1e/ie/user-id.go#L224

Should it be 'has4thBit' ?

If enable bit 1 with out enable NAI, it will crash.

**Comment by wmnsk** [comment]
Good catch, thanks! Fixed in #89.

**Comment by chengtontom** [comment]
> Good catch, thanks! Fixed in #89.
Thanks for the fix. ^.^
